name: Stories
favicon: null
layout_spectrum: 0.09055302198976278
typography_spectrum: 0.7454038367141038
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.5704360713716596
  lightness: 0.7587312317918986
  saturation: 0.3962981216609478
  rhythmicContrast: 0.5458291179966182
purpose: []
